Fixed NullPointer in Android reject method. [DA-2077]
NullPointerException: Parameter specified as non-null is null: method com.facebook.react.bridge.PromiseImpl.reject, parameter code

Related:
 - https://planitar.atlassian.net/browse/DA-2077